apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "scalarlm.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "scalarlm.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "scalarlm.labels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      hostname: {{ include "scalarlm.fullname" . }}
      dnsConfig:
        searches:
          - {{ include "scalarlm.megatronname" . }}-headless.{{ .Release.Namespace }}.svc.cluster.local
          - "{{ .Release.Namespace }}.svc.cluster.local"
          - "svc.cluster.local"
          - "cluster.local"
        options:
          - name: ndots
            value: "1"
      {{- include "scalarlm.scheduling" . | nindent 6 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/cray/scripts/start_one_server.sh"]
          env:
            - name: NCCL_IB_GID_INDEX
              value: "1"
            - name: NCCL_IB_HCA
              value: "rdma0,rdma1,rdma2,rdma3,rdma4,rdma5,rdma6,rdma7"
            - name: NCCL_SOCKET_IFNAME
              value: "eth0"
            - name: GLOO_SOCKET_IFNAME
              value: "eth0"
            - name: NCCL_SOCKET_FAMILY
              value: "AF_INET"
            - name: NCCL_NET_GDR_LEVEL
              value: "SYS"
            - name: ROCR_VISIBLE_DEVICES
              value: "0"
            - name: HIP_VISIBLE_DEVICES
              value: "0"
            - name: CRAY_TRAIN_DEBUG
              value: "0"
            - name: HSA_NO_SCRATCH_RECLAIM
              value: "1"
          ports:
            - name: http
              containerPort: {{ .Values.service.api_port }}
              hostPort: {{ .Values.service.api_port }}
              protocol: TCP
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .path }}
          {{- end }}
            - name: scalarlm-config
              mountPath: /app/cray/cray-config.yaml
              subPath: cray-config.yaml
            - name: scalarlm-jobs
              mountPath: /app/cray/jobs
            - name: scalarlm-cache
              mountPath: /root/.cache/huggingface
            - name: scalarlm-slurm-config
              mountPath: /app/cray/nfs
      volumes:
        - name: scalarlm-jobs
          persistentVolumeClaim:
            claimName: scalarlm-jobs
        - name: scalarlm-cache
          persistentVolumeClaim:
            claimName: scalarlm-cache
        - name: scalarlm-slurm-config
          persistentVolumeClaim:
            claimName: scalarlm-slurm-config
        - name: scalarlm-config
          configMap:
            name: {{ .Release.Name }}-api-configmap
      {{- range .Values.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostPath }}
      {{- end }}

